=== Williambrai97/Esercitazioni-e-Progetti/bellinifacsimile.dtd
<!ELEMENT TEI (teiHeader, text, facsimile)>
<!ELEMENT teiHeader (fileDesc, encodingDesc)>
<!ELEMENT text (body)>
<!ELEMENT facsimile (surface)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
<!ELEMENT encodingDesc (p)>
<!ELEMENT body (div)>
<!ELEMENT surface (graphic, zone+)>
<!ELEMENT titleStmt (title, author, respStmt)>
<!ELEMENT publicationStmt (p, publisher+, avalability)>
<!ELEMENT sourceDesc (bibl)>
<!ELEMENT p (#PCDATA|seg)*>
<!ELEMENT div (pb, opener, p)>
<!ELEMENT graphic EMPTY>
<!ELEMENT zone EMPTY>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT respStmt (resp, name)>
<!ELEMENT publisher (#PCDATA|date)*>
<!ELEMENT avalability (p)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT bibl (title, author, pubPlace, date)>
<!ELEMENT opener (dateline, salute)>
<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT pubPlace (#PCDATA)>
<!ELEMENT dateline (#PCDATA|num|pc|choice|space|placeName)*>
<!ELEMENT placeName (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT salute (#PCDATA|damage)*>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT space EMPTY>
<!ELEMENT pc (#PCDATA)>
<!ELEMENT choice (abbr, expan)>
<!ELEMENT abbr (#PCDATA)>
<!ELEMENT expan (#PCDATA|ex)*>
<!ELEMENT ex (#PCDATA)>
<!ELEMENT seg (#PCDATA)>
<!ELEMENT pb EMPTY>
<!ATTLIST TEI xmlns CDATA "http://www.tei-c.org/ns/1.0">
<!ATTLIST avalability status (free|unknown|restricted) #IMPLIED>
<!ATTLIST date when CDATA #IMPLIED>
<!ATTLIST div type CDATA #IMPLIED>
<!ATTLIST placeName country CDATA #IMPLIED>
<!ATTLIST placeName rend CDATA #IMPLIED>
<!ATTLIST dateline lang CDATA #IMPLIED>
<!ATTLIST num type (cardinal|ordinal|fraction|percentage) #IMPLIED>
<!ATTLIST damage agent CDATA #IMPLIED>
<!ATTLIST space dim (vertical|horizontal) #IMPLIED>
<!ATTLIST pc unit CDATA #IMPLIED>
<!ATTLIST abbr type (suspension|contraction|brevigraph|superscription|acronym|title|organization|geographic) #IMPLIED>
<!ATTLIST seg rend CDATA #IMPLIED>
<!ATTLIST pb facs CDATA  #IMPLIED>
<!ATTLIST pb xml:id ID #IMPLIED>
<!ATTLIST dateline facs CDATA  #IMPLIED>
<!ATTLIST salute facs CDATA  #IMPLIED>
<!ATTLIST p facs CDATA  #IMPLIED>
<!ATTLIST surface xml:id ID #IMPLIED>
<!ATTLIST surface start CDATA #IMPLIED>
<!ATTLIST surface ulx CDATA #IMPLIED>
<!ATTLIST surface uly CDATA #IMPLIED>
<!ATTLIST surface lrx CDATA #IMPLIED>
<!ATTLIST surface lry CDATA #IMPLIED>
<!ATTLIST graphic url CDATA #REQUIRED>
<!ATTLIST zone xml:id ID #IMPLIED>
<!ATTLIST zone ulx CDATA #IMPLIED>
<!ATTLIST zone uly CDATA #IMPLIED>
<!ATTLIST zone lrx CDATA #IMPLIED>
<!ATTLIST zone lry CDATA #IMPLIED>

=== Williambrai97/Esercitazioni-e-Progetti/bellinifacsimile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI SYSTEM "bellinifacsimile.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>Lettera di Vincenzo Bellini a Carlo Pepoli</title>
                <author>Vincenzo Bellini</author>
                <respStmt>
                    <resp>Testo codificato da ms originale in TEI P5 a cura di</resp>
                    <name>William Brai</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <p>Testo codificato per esercizio</p>
                <publisher>Pastura<date when="1959">1959</date></publisher>
                <publisher>Neri<date when="2005">2005</date></publisher>
                <avalability status="restricted"><p>Opera riportata nelle slide del corso di codifica di testi</p></avalability>
            </publicationStmt>
            <sourceDesc>
                <bibl>
                    <title>Vincenzo Bellini a Carlo Pepoli</title>
                    <author>Vincenzo Bellini</author>
                    <pubPlace>Puteaux</pubPlace>
                    <date when="26/06/1834">26 giugno 1834</date>
                </bibl>
            </sourceDesc>
        </fileDesc>
        <encodingDesc>
            <p>Codifica in Tei versione P5 partendo un'immagine della lettera</p>
        </encodingDesc>
    </teiHeader>
    <text>
        <body>
            <div type="lettera">
                <pb facs="#page1" xml:id="page-1"/>
                <opener>
                    <dateline facs="#intestazione"  lang ="FR">Juin <num>26</num><pc unit="Colon">:</pc> <placeName country="France">Puteau</placeName> <pc unit="Hyphen-minus">–</pc> <choice><abbr type="acronym">N</abbr><expan>N<ex>umero</ex></expan></choice><pc unit="Colon">:</pc><num type="ordinal">19</num> bis rampe <space dim="vertical"/><placeName rend="underline">de Neuilly</placeName></dateline>
                    <salute facs="#saluto">Mio caro Car<damage agent="time">lu</damage>ccio</salute>
                </opener>
                <p facs="#contenuto">avendo steso l’intero <seg rend="Bold">duetto</seg></p>
            </div>
        </body>
    </text>
    <facsimile>
        <surface xml:id="page1" start="#page-1" ulx="0" uly="0" lrx="1273" lry="452">
            <graphic url="bellini.png"/>
            <zone xml:id="intestazione" ulx="1" uly="3" lrx="1271" lry="190" />
            <zone xml:id="saluto" ulx="187" uly="189" lrx="941" lry="268" />
            <zone xml:id="contenuto" ulx="304" uly="339" lrx="1269" lry="448" />
        </surface>
    </facsimile>
</TEI>
